version: '3.8'

networks:
  architecturesamplenetwork:       

volumes:
  RedisData:
    driver: local

services:
  SqlServerInstance:
    container_name: ArchitectureSample-SqlServerInstance
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Hoorbakht@321

  WebApi:
    container_name: ArchitectureSample-WebApi
    image: architecturesample:dev
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - SqlServerInstance
      - RedisInstance
      - MongoInstance
    restart: on-failure

  BlazorClient:
    container_name: ArchitectureSample-BlazorClient
    image: architecturesample/blazor/client:dev
    ports:
      - "9191:80"
    build:
      context: .
      dockerfile: Dockerfile-Blazor-Client
    depends_on:
      - WebApi 
  
  BlazorServer:
    container_name: ArchitectureSample-BlazorServer
    image: architecturesample/blazor/server:dev
    ports:
      - "9091:8080"
    build:
      context: .
      dockerfile: Dockerfile-Blazor-Server
    depends_on:
      - BlazorClient 
  
  RedisInstance:
    container_name: ArchitectureSample-Redis
    image: redis:latest
    restart: always
    ports:
      - '3232:6379'
    volumes: 
      - RedisData:/data

  MongoInstance:
    container_name: ArchitectureSample-Mongo
    image: mongo:latest
    restart: always
    ports:
      - '27027:27017'
    networks:
      - architecturesamplenetwork

  PrometheusInstance:
    image: prom/prometheus
    container_name: ArchitectureSample-Prometheus
    ports:
      - '2390:9090'
    volumes:
      - "./MonitoringFiles/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - architecturesamplenetwork
    depends_on:
      - WebApi
    restart: on-failure
  
  NodeExporterInstance:
    container_name: ArchitectureSample-NodeExporter
    image: prom/node-exporter
    networks:
      - architecturesamplenetwork
    ports:
      - 9100:9100
  
  GrafanaInstance:
    image: 'grafana/grafana:latest'
    container_name: ArchitectureSample-Grafana
    ports:
      - '3000:3000'
    depends_on:
      - PrometheusInstance
    volumes:
      - ./MonitoringFiles/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin@321
    networks:
      - architecturesamplenetwork
    restart: on-failure