version: '3.8'

networks:
  architecturesamplenetwork:       

services:
  SqlServerInstance:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Hoorbakht@321

  WebApi:
    container_name: architecturesample-api
    image: architecturesample:dev
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - SqlServerInstance
    restart: on-failure

  BlazorClient:
    container_name: architecturesample-blazor-client
    image: architecturesample/blazor/client:dev
    ports:
      - "9191:80"
    build:
      context: .
      dockerfile: Dockerfile-Blazor-Client
    depends_on:
      - WebApi 
  
  BlazorServer:
    container_name: architecturesample-blazor-server
    image: architecturesample/blazor/server:dev
    ports:
      - "9091:8080"
    build:
      context: .
      dockerfile: Dockerfile-Blazor-Server
    depends_on:
      - BlazorClient 
