version: '3.8'

networks:
  architecturesamplenetwork:       

services:
  SqlServerInstance:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Hoorbakht@321

  WebApi:
    container_name: api
    image: architecturesample:dev
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - SqlServerInstance
    restart: on-failure
